### ISSUE TITLE
Satisfy GitLab dependencies for Pipeline tests

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/uds-capability-gitlab#9]
As a GitLab capability developer
I need to satisfy GitLab dependencies in CI pipelines
So that I have confidence that GitLab will deploy successfully

Deploy PostgreSQL, Redis, and MinIO (?) as part of setup

**Comment by corang** [comment]
Database confirmed working, in cluster postgres example (and for testing) here https://github.com/defenseunicorns/uds-package-software-factory/tree/main/utils/pkg-deps/gitlab-postgres

**Comment by zachariahmiller** [comment]
In case anyone comes back to this later, the aforementioned link is now [here](https://github.com/defenseunicorns/uds-package-software-factory/tree/main/utils/pkg-deps/gitlab/postgres)

**Comment by Michael-Kruggel** [comment]
All requirements are met, closing issue
